name: cvat

services:
  elasticsearch:
    container_name: cvat_elasticsearch
    image: cvat_elasticsearch
    build:
      context: ./elasticsearch
      args:
        ELK_VERSION: 6.8.23
    volumes:
      - cvat_events:/usr/share/elasticsearch/data
    restart: always

  kibana:
    container_name: cvat_kibana
    image: cvat_kibana
    build:
      context: ./kibana
      args:
        ELK_VERSION: 6.8.23
    depends_on: ['elasticsearch']
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    restart: always
    ports:
      - '5601:5601'

  cvat_kibana_setup:
    container_name: cvat_kibana_setup
    image: cvat/server:${CVAT_VERSION:-dev}
    volumes: ['./components/analytics/deprecated/kibana:/home/django/kibana:ro']
    working_dir: '/home/django'
    entrypoint:
      [
        'bash',
        'wait-for-it.sh',
        'elasticsearch:9200',
        '-t',
        '0',
        '--',
        '/bin/bash',
        'wait-for-it.sh',
        'kibana:5601',
        '-t',
        '0',
        '--',
        'python3',
        'kibana/setup.py',
        'kibana/export.json',
      ]
    environment:
      no_proxy: elasticsearch,kibana,${no_proxy:-}

volumes:
  cvat_events:
